id: opecha:P008144
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12782
  title: བོད་དང་ཧི་མཱ་ལ་ཡར་ཡོད་པའི་བོན་དགོན་དང་ལྷ་ཁང་གི་སྤྱི་བཤད།
  volume:
    4201784b454540eeb962790f765e5b4d:
      image_group_id: I1KG12880
      title: Volume 1 of a survey of bonpo monasteries and temples in tibet and the
        himalaya
      volume_number: 1
      total_pages: 900
  author: ''
ebook_metadata:
  title: བོད་དང་ཧི་མཱ་ལ་ཡར་ཡོད་པའི་བོན་དགོན་དང་ལྷ་ཁང་གི་སྤྱི་བཤད།
  author: ''
  sku: P008144
  cover: cover.jpg
  layers:
  - pagination
