id: P008144
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12782
  title: བོད་དང་ཧི་མཱ་ལ་ཡར་ཡོད་པའི་བོན་དགོན་དང་ལྷ་ཁང་གི་སྤྱི་བཤད།
  author: ''
  volumes:
    f8b361e5ac944a6d8aaefa17bb1ea594:
      image_group_id: I1KG12880
      title: ''
      volume_number: 1
      total_pages: 900
ebook_metadata:
  title: བོད་དང་ཧི་མཱ་ལ་ཡར་ཡོད་པའི་བོན་དགོན་དང་ལྷ་ཁང་གི་སྤྱི་བཤད།
  author: ''
  sku: P008144
  cover: cover.jpg
  layers:
  - pagination
